defaults:
  - _self_
  - dataset: ABIDE
  - model: cwbrainnet
  - optimizer: adam
  - training: basic

main_path: ./CBN
checkpoints: ./CBN/checkpoints
init_method: tcp://<your-ip-address>:<port>  # specify for distributed setup

gpu: 0
seed: 42

n_fold: 5
n_iter: 5
